/*
 * system.h
 *
 *  Created on: 2014/05/20
 *      Author: kirk
 */

#ifndef SYSTEM_H_
#define SYSTEM_H_


#define MAINMEM_BASEADDR 0

//#define MAX_WIDTH  2048
//#define MAX_HEIGHT 1536
//#define MAX_WIDTH  1600
//#define MAX_HEIGHT 1200
#define MAX_WIDTH  1280
#define MAX_HEIGHT 1024
//#define MAX_WIDTH  1024
//#define MAX_HEIGHT 768

#define FRAME0_NUM	1
#define FRAME1_NUM	1

#define FRAME0_OFFSET 		0x10000000
#define FRAME1_OFFSET 		0x11000000

#define FRAME0_SIZE (MAX_WIDTH * MAX_HEIGHT * 4)
#define FRAME1_SIZE (MAX_WIDTH * MAX_HEIGHT * 4)

#define REGBANK_SIZE	16

#define VIDEOOUT_BANK_NUM	8
#define IMAGEIN_BANK_NUM	4

#define ATRJ_SW_BASEADDR		(XPAR_GPIO_0_BASEADDR)
#define ATRJ_LED_BASEADDR		(XPAR_GPIO_0_BASEADDR + 8)

#ifdef XPAR_VIDEO_OUT_0_BASEADDR
#define ATRJ_VDC0_BASEADDR		(XPAR_VIDEO_OUT_0_BASEADDR)
#define ATRJ_CLKGEN_BASEADDR	(XPAR_VIDEO_OUT_0_BASEADDR + REGBANK_SIZE * 2)
#define ATRJ_VMUX_BASEADDR		(XPAR_VIDEO_OUT_0_BASEADDR + REGBANK_SIZE * 4)

#define ATRJ_FCNT_BASEADDR		(XPAR_VIDEO_OUT_0_BASEADDR + REGBANK_SIZE * 7)

#define ATRJ_VFREQ_BASEADDR		(XPAR_VIDEO_OUT_0_BASEADDR + REGBANK_SIZE * (VIDEOOUT_BANK_NUM + 2))
#endif

#ifdef XPAR_IMAGE_IN_0_BASEADDR
#define ATRJ_IGC0_BASEADDR		(XPAR_IMAGE_IN_0_BASEADDR)
#define ATRJ_IMUX_BASEADDR		(XPAR_IMAGE_IN_0_BASEADDR + REGBANK_SIZE * 1)
#define ATRJ_IGCC0NT_BASEADDR	(XPAR_IMAGE_IN_0_BASEADDR + REGBANK_SIZE * (IMAGEIN_BANK_NUM + 0))
#define ATRJ_IFREQ_BASEADDR		(XPAR_IMAGE_IN_0_BASEADDR + REGBANK_SIZE * (IMAGEIN_BANK_NUM + 2))
#define ATRJ_APTIIC_BASEADDR	(XPAR_PS7_I2C_0_BASEADDR)

#endif

#ifdef XPAR_CI_PIPE_0_S_AXI_AXILITES_BASEADDR
#define ATRJ_CI0_BASEADDR	XPAR_CI_PIPE_0_S_AXI_AXILITES_BASEADDR
#endif

#ifdef XPAR_PS7_I2C_1_BASEADDR
#define ATRJ_HDMIIIC_BASEADDR		(XPAR_PS7_I2C_1_BASEADDR)
#define ADV7511_ADDR	0x39
#endif

#define CI_MODE		0

#define IMG_BITS		12
#define COLOR_BITS		8

#define ROUND_BITS	(IMG_BITS - COLOR_BITS)

#define IMAGER_WIDTH	MAX_WIDTH
#define IMAGER_HEIGHT	MAX_HEIGHT


#endif /* SYSTEM_H_ */
