// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of mode
//        bit 2~0 - mode[2:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of sft
//        bit 7~0 - sft[7:0] (Read/Write)
//        others  - reserved
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCI_PIPE_AXILITES_ADDR_MODE_DATA 0x10
#define XCI_PIPE_AXILITES_BITS_MODE_DATA 3
#define XCI_PIPE_AXILITES_ADDR_SFT_DATA  0x18
#define XCI_PIPE_AXILITES_BITS_SFT_DATA  8

