// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XCI_PIPE_H
#define XCI_PIPE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xci_pipe_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XCi_pipe_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XCi_pipe;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCi_pipe_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCi_pipe_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCi_pipe_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCi_pipe_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCi_pipe_Initialize(XCi_pipe *InstancePtr, u16 DeviceId);
XCi_pipe_Config* XCi_pipe_LookupConfig(u16 DeviceId);
int XCi_pipe_CfgInitialize(XCi_pipe *InstancePtr, XCi_pipe_Config *ConfigPtr);
#else
int XCi_pipe_Initialize(XCi_pipe *InstancePtr, const char* InstanceName);
int XCi_pipe_Release(XCi_pipe *InstancePtr);
#endif


void XCi_pipe_Set_mode(XCi_pipe *InstancePtr, u32 Data);
u32 XCi_pipe_Get_mode(XCi_pipe *InstancePtr);
void XCi_pipe_Set_sft(XCi_pipe *InstancePtr, u32 Data);
u32 XCi_pipe_Get_sft(XCi_pipe *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
